// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using piedteam_net1_2_hocmienphi.repository;

#nullable disable

namespace piedteam_net1_2_hocmienphi.repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812135633_sendDate")]
    partial class sendDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.ApplyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CvLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ApplyRequests");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.ApplyRequestCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplyRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ApplyRequestId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ApplyRequestCategories");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.Mentor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentPosition")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.MentorCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MentorId");

                    b.ToTable("MentorCategories");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.MentorFreeTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DateOfWeek")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.ToTable("MentorFreeTimes");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSendAdvertising")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SendDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.ApplyRequest", b =>
                {
                    b.HasOne("piedteam_net1_2_hocmienphi.repository.Entity.User", "User")
                        .WithMany("ApplyRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.ApplyRequestCategory", b =>
                {
                    b.HasOne("piedteam_net1_2_hocmienphi.repository.Entity.ApplyRequest", "ApplyRequest")
                        .WithMany("ApplyRequestsCategories")
                        .HasForeignKey("ApplyRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("piedteam_net1_2_hocmienphi.repository.Entity.Category", "Category")
                        .WithMany("ApplyRequestsCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplyRequest");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.Booking", b =>
                {
                    b.HasOne("piedteam_net1_2_hocmienphi.repository.Entity.Mentor", "Mentor")
                        .WithMany("Bookings")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("piedteam_net1_2_hocmienphi.repository.Entity.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.Category", b =>
                {
                    b.HasOne("piedteam_net1_2_hocmienphi.repository.Entity.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.Mentor", b =>
                {
                    b.HasOne("piedteam_net1_2_hocmienphi.repository.Entity.Category", null)
                        .WithMany("Mentors")
                        .HasForeignKey("CategoryId");

                    b.HasOne("piedteam_net1_2_hocmienphi.repository.Entity.User", "User")
                        .WithOne("Mentor")
                        .HasForeignKey("piedteam_net1_2_hocmienphi.repository.Entity.Mentor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.MentorCategory", b =>
                {
                    b.HasOne("piedteam_net1_2_hocmienphi.repository.Entity.Category", "Category")
                        .WithMany("MentorCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("piedteam_net1_2_hocmienphi.repository.Entity.Mentor", "Mentor")
                        .WithMany("MentorCategories")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.MentorFreeTime", b =>
                {
                    b.HasOne("piedteam_net1_2_hocmienphi.repository.Entity.Mentor", "Mentor")
                        .WithMany("MentorFreeTimes")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.ApplyRequest", b =>
                {
                    b.Navigation("ApplyRequestsCategories");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.Category", b =>
                {
                    b.Navigation("ApplyRequestsCategories");

                    b.Navigation("Children");

                    b.Navigation("MentorCategories");

                    b.Navigation("Mentors");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.Mentor", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("MentorCategories");

                    b.Navigation("MentorFreeTimes");
                });

            modelBuilder.Entity("piedteam_net1_2_hocmienphi.repository.Entity.User", b =>
                {
                    b.Navigation("ApplyRequests");

                    b.Navigation("Bookings");

                    b.Navigation("Mentor");
                });
#pragma warning restore 612, 618
        }
    }
}
